### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by RustyUncle** [davidjoseph9/AntiCheatSoftware-Bypass#4]
Can you bypass any game of Nexon like Vindictus?

**Comment by davidjoseph9** [comment]
Hello RustyUncle, I'm not familiar with the game Vindictus. Is it also protected by Nexon Game Security / BlackCipher?

**Comment by RustyUncle** [comment]
> Hello RustyUncle, I'm not familiar with the game Vindictus. Is it also protected by Nexon Game Security / BlackCipher?

Yes, it is

**Comment by davidjoseph9** [comment]
Then I sure can; if you're lucky, they may be using the same version of Nexon Game Security as MapleStory; There are some MapleStory specific patches included in repository though.

**Comment by RustyUncle** [comment]
I hope you'll handle it as soon as
